In [1]:
import numpy as np

In [2]:
a1 = np.array ([10,20,30])
a1

array([10, 20, 30])

In [4]:
a1 = np.array ([[10,20,30], [50,51,52]])
a1

array([[10, 20, 30],
       [50, 51, 52]])

In [7]:
l1 = [10,20,30]
a1 =np.array (l1)
a1

array([10, 20, 30])

In [8]:
l1 = [[10,20,30],[30,31,32]]
a1 =np.array (l1)
a1

array([[10, 20, 30],
       [30, 31, 32]])

In [9]:
list1 = [[10,20,30],[50,60,70]]
print (list1)


[[10, 20, 30], [50, 60, 70]]


In [10]:
a= np.array ([[10,20,30],[50,60,70]])
print (a)


[[10 20 30]
 [50 60 70]]


In [12]:
a= np.array ([[10,20,30],[50,70]])
print (a)


[list([10, 20, 30]) list([50, 70])]


C:\Users\noble\AppData\Local\Temp\ipykernel_21036\1257682112.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a= np.array ([[10,20,30],[50,70]])


In [13]:
a= np.array ([[10,20,30],[50,0,70]])
print (a)

[[10 20 30]
 [50  0 70]]


In [14]:
a= np.array ([[10,20,30],[50,np.nan,70]])
print (a)

[[10. 20. 30.]
 [50. nan 70.]]


In [15]:
a= np.array ([[10,20,30],[50,'Sat',70]])
print (a)

[['10' '20' '30']
 ['50' 'Sat' '70']]


In [16]:
list1 = [10,20,30,40,50]
import numpy as np
array1 = np.array (list1)
print (type(array1))
print (type(list1))
print (array1)


<class 'numpy.ndarray'>
<class 'list'>
[10 20 30 40 50]


In [17]:
list1 = [10,20,30,40,50,'X']
import numpy as np
array1 = np.array (list1)
print (type(array1))
print (type(list1))
print (list1)
print (array1)


<class 'numpy.ndarray'>
<class 'list'>
[10, 20, 30, 40, 50, 'X']
['10' '20' '30' '40' '50' 'X']


In [19]:
Tup1 = (10,20,30,40,50,'x','y')
import numpy as np
array1 = np.array (Tup1)
array1

array(['10', '20', '30', '40', '50', 'x', 'y'], dtype='<U11')