In [1]:
import numpy 
a = numpy.array ([10,20,30])
print (a)  

[10 20 30]


In [2]:
a = numpy.array ([10,20,30])
print (a)

[10 20 30]


In [3]:
import numpy as np

In [2]:
a = np.array ([10,20,30])
print (a)

[10 20 30]


In [3]:
array1 = np.array ([10,12,14,16,20])
print (array1)


[10 12 14 16 20]


In [4]:
list1 = [[10,20,30],[50,60,70]]
print (list1)


[[10, 20, 30], [50, 60, 70]]


In [5]:
array1 = np.array (list1)
print (array1)


[[10 20 30]
 [50 60 70]]


In [11]:
list1 = [[10,20,30],[50,60,'Sat']]
print (list1)
print ()
array1 = np.array (list1)
print (array1)

[[10, 20, 30], [50, 60, 'Sat']]

[['10' '20' '30']
 ['50' '60' 'Sat']]


In [12]:
ar1 = np.array([[10,20,30,40],[50,60,70, np.nan]])
ar1


array([[10., 20., 30., 40.],
       [50., 60., 70., nan]])

In [13]:
Tup1 = (10,20,30,40,50,'x','y')
import numpy as np
array1 = np.array (Tup1)
print (type(array1))
print (type(Tup1))
print (Tup1)
print (array1)


<class 'numpy.ndarray'>
<class 'tuple'>
(10, 20, 30, 40, 50, 'x', 'y')
['10' '20' '30' '40' '50' 'x' 'y']


In [15]:
list1 = [10,20,30,40,50,60,70,80]
list1

[10, 20, 30, 40, 50, 60, 70, 80]

In [16]:
array1 = np.array (list1)
print (array1)
array2 = array1 [:3]
print (array2)
array2 [0] =500
print (array1)
print (array2)


[10 20 30 40 50 60 70 80]
[10 20 30]
[500  20  30  40  50  60  70  80]
[500  20  30]


In [19]:
list1 = [10,20,30,40,50,60,70,80]
array1 = np.array (list1)
print (array1)

[10 20 30 40 50 60 70 80]


In [21]:
list1 = [10,20,30,40,50,60,70,80]
array1 = np.array (list1)
print (array1)


[10 20 30 40 50 60 70 80]


In [22]:
array2 = array1 [:3].copy() 
print (array2)
array2 [0] =500
print (array1)
print (array2)

[10 20 30]
[10 20 30 40 50 60 70 80]
[500  20  30]


In [23]:
a = np.arange (5)
a

array([0, 1, 2, 3, 4])

In [4]:
a = np.arange (5)
a

array([0, 1, 2, 3, 4])

In [24]:
list1 = [10,20,30,40,50,60,70,80]
array1 = np.array (list1)
array1

array([10, 20, 30, 40, 50, 60, 70, 80])

In [26]:
a5 = array1[2:5].copy()
a5

array([30, 40, 50])

In [28]:
a5[1]= 444

In [29]:
a5

array([ 30, 444,  50])

In [30]:
array1

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
a5 = array1[2:5]
a5[1]= 777

In [36]:
print (a5)

[ 30 777  50]


In [37]:
array1

array([ 10,  20,  30, 777,  50,  60,  70,  80])

In [38]:
a = np.arange (10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a = np.arange (20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
a = np.arange (10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
a = np.arange (10,20,2)
a

array([10, 12, 14, 16, 18])

In [42]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
a = a.reshape((3,3))
print (a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
b = a.reshape((10,3))
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [46]:
b = a.reshape((6,5))
print (b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [47]:
b = a.reshape((2,5,3))
print (b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [49]:
b = a.reshape((9,3))
print (b)

ValueError: cannot reshape array of size 30 into shape (9,3)

In [51]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [52]:
b = np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
b = np.ones((4,9))
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
b*5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [55]:
b *-3

array([[-3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3.]])

In [56]:
mat1 = np.arange (0,30)
mat2 =np.reshape (mat1,(6,5),'F')
print (mat1)
print (mat2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [57]:
mat2 =np.reshape (mat1,(6,5),'F')
print (mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [58]:
mat2 =np.reshape (mat1,(6,5),'C')
print (mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [60]:
mat2 =np.reshape (mat1,(6,5))
print (mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [61]:
mat2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [63]:
mat2.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [69]:
a = np.arange (9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
b = a.reshape (3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
a= np.arange (2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
c= a.reshape (3,3)
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [73]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [75]:
b+c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [76]:
c-b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [77]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [78]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
c*b

array([[ 0,  3,  8],
       [15, 24, 35],
       [48, 63, 80]])

In [81]:
c/b

C:\Users\noble\AppData\Local\Temp\ipykernel_13464\3697610823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c/b


array([[       inf, 3.        , 2.        ],
       [1.66666667, 1.5       , 1.4       ],
       [1.33333333, 1.28571429, 1.25      ]])

In [82]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [84]:
b@c

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [85]:
0+5+16

21

In [86]:
b%c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
b//c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
b**c

array([[         0,          1,         16],
       [       243,       4096,      78125],
       [   1679616,   40353607, 1073741824]])

In [90]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [92]:
b==c

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [93]:
b <c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [94]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [98]:
b@c

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])

In [99]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
b.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
vector = np.linspace(0,30,11)
print (vector)


[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]


In [102]:
vector = np.linspace(10,40,5)
print (vector)


[10.  17.5 25.  32.5 40. ]


In [103]:
vector = np.linspace(10,20,4)
print (vector)


[10.         13.33333333 16.66666667 20.        ]


In [104]:
EU_Sales = [1002, 4523,4123,3584]
APAC_Sales = [7854,9654,4582,8543]
US_Sales = [7845,4512,3652,7452]


In [105]:
Sales = np.array ([EU_Sales, APAC_Sales,US_Sales])
print (Sales)


[[1002 4523 4123 3584]
 [7854 9654 4582 8543]
 [7845 4512 3652 7452]]


In [108]:
Sales[1][3]

8543

In [109]:
Sales[2][1]

4512

In [110]:
r= {'EU':0,'APAC':1,'US':2}
q ={'Q1':0,'Q2':1,'Q3':2,'Q4':3}


In [111]:
Sales

array([[1002, 4523, 4123, 3584],
       [7854, 9654, 4582, 8543],
       [7845, 4512, 3652, 7452]])

In [113]:
Sales[1][2]

4582

In [114]:
r['APAC']

1

In [116]:
Sales[r['APAC']][q['Q3']]

4582

In [117]:
Sales

array([[1002, 4523, 4123, 3584],
       [7854, 9654, 4582, 8543],
       [7845, 4512, 3652, 7452]])

In [118]:
Sales[r['EU']][q['Q1']]

1002

In [119]:
arr1= np.arange (100,200)
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [120]:
print (arr1[10:],'\n')

[110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199] 



In [121]:
print (arr1[:20],'\n')

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119] 



In [122]:
print (arr1[10:20],'\n')
print (arr1[10:50:5])


[110 111 112 113 114 115 116 117 118 119] 

[110 115 120 125 130 135 140 145]


In [123]:
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [124]:
arr_slice = slice (1,10,2)
print (arr_slice)
print (arr1[arr_slice])


slice(1, 10, 2)
[101 103 105 107 109]


In [125]:
arr1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [126]:
arr1 =  np.arange(9)
print (arr1)
arr1=arr1.reshape(3,3)
print ('\n')
print (arr1)


[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [127]:
4 5
7 8

SyntaxError: invalid syntax (4290325231.py, line 1)

In [131]:
arr1[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [132]:
arr2 = arr1[0:2,0:2]
print (arr2)


[[0 1]
 [3 4]]


In [133]:
print (arr1)
print (arr1.shape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [134]:
print (arr1.ndim)

2


In [135]:
print (arr1.itemsize)

4


In [136]:
print (arr1.dtype)

int32


In [137]:
print (arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [138]:
print (arr1.size)

9


In [139]:
print (arr1.min())
print (arr1.max())


0
8


In [141]:
print (arr1.sum())

36


In [143]:
print (np.sqrt(arr1))


[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [144]:
print (np.std(arr1))


2.581988897471611


In [145]:

arr5 = np.empty([3,2], dtype =  float)
print (arr5)



[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 8.01101963e-307]
 [1.89146896e-307 7.56571288e-307]]


In [146]:
arr5 = np.empty([3,2], dtype =  int)
print (arr5)


[[10 20]
 [30 50]
 [60 70]]


In [147]:
arr5 = np.empty([3,2], dtype =  bool)
print (arr5)


[[ True  True]
 [ True  True]
 [ True  True]]


In [148]:
arr5 = np.empty([3,2], dtype =  str)
print (arr5)


[['' '']
 ['' '']
 ['' '']]


In [149]:
dir (numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [150]:
import numpy 
for name in dir(numpy):
    print (name, end = '\t')   


ALLOW_THREADS	AxisError	BUFSIZE	CLIP	ComplexWarning	DataSource	ERR_CALL	ERR_DEFAULT	ERR_IGNORE	ERR_LOG	ERR_PRINT	ERR_RAISE	ERR_WARN	FLOATING_POINT_SUPPORT	FPE_DIVIDEBYZERO	FPE_INVALID	FPE_OVERFLOW	FPE_UNDERFLOW	False_	Inf	Infinity	MAXDIMS	MAY_SHARE_BOUNDS	MAY_SHARE_EXACT	ModuleDeprecationWarning	NAN	NINF	NZERO	NaN	PINF	PZERO	RAISE	RankWarning	SHIFT_DIVIDEBYZERO	SHIFT_INVALID	SHIFT_OVERFLOW	SHIFT_UNDERFLOW	ScalarType	Tester	TooHardError	True_	UFUNC_BUFSIZE_DEFAULT	UFUNC_PYVALS_NAME	VisibleDeprecationWarning	WRAP	_CopyMode	_NoValue	_UFUNC_API	__NUMPY_SETUP__	__all__	__builtins__	__cached__	__config__	__deprecated_attrs__	__dir__	__doc__	__expired_functions__	__file__	__getattr__	__git_version__	__loader__	__name__	__package__	__path__	__spec__	__version__	_add_newdoc_ufunc	_distributor_init	_financial_names	_from_dlpack	_globals	_mat	_pytesttester	_version	abs	absolute	add	add_docstring	add_newdoc	add_newdoc_ufunc	alen	all	allclose	alltrue	amax	amin	angle	any	append	apply_along_axis	appl

In [151]:
arr = np.array([1, 2, 3, 4, 5]) 
print (arr)
print (arr.dtype)
print ('\n')


[1 2 3 4 5]
int32




In [152]:
float_arr = arr.astype(np.float64) 
print (float_arr)
print (float_arr.dtype)


[1. 2. 3. 4. 5.]
float64


In [153]:
float_arr = arr.astype(np.bool) 
print (float_arr)
print (float_arr.dtype)


[ True  True  True  True  True]
bool


C:\Users\noble\AppData\Local\Temp\ipykernel_13464\4261788772.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  float_arr = arr.astype(np.bool)


In [154]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [155]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [156]:
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [157]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
arr

array([[3, 2, 4],
       [5, 0, 1]])

In [158]:
print (np.sort(arr, axis = 0))



[[3 0 1]
 [5 2 4]]


In [159]:

print (np.sort(arr, axis = 1))


[[2 3 4]
 [0 1 5]]


In [161]:
arr= np.arange(10,19)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [160]:


arr= np.delete (arr, [2,5,8])
print (arr)


[10 11 13 14 16 17]


In [162]:
arr= np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [163]:
a= np.delete (arr2,1,0)
a


array([[10, 11, 12, 13],
       [18, 19, 20, 21]])

In [164]:
arr= np.arange(10,22)
arr2 = arr.reshape(3,4)
arr2


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [165]:
b= np.delete (arr2,1,1)
b

array([[10, 12, 13],
       [14, 16, 17],
       [18, 20, 21]])