In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
print(np.__version__)


1.24.3


In [5]:
new = np.array([1, 2, 3, 4, 5])
print(new)


[1 2 3 4 5]


In [6]:
type(new)

numpy.ndarray

In [7]:
new = np.array((1, 2, 3, 4, 5))
print(new)

[1 2 3 4 5]


In [9]:
#0-D
new = np.array(23)
print(new)

23


In [11]:
#1-D
new=np.array([12])
new

array([12])

In [12]:
#2-D
new=np.array([[12],[23]])
print(new)

[[12]
 [23]]


In [14]:
#3-D
new=np.array([[[12],[23]],[[45],[23]]])
print(new)

[[[12]
  [23]]

 [[45]
  [23]]]


In [15]:
print(new.ndim)

3


In [16]:
new= np.array([1, 2, 3, 4], ndmin=5)

print(new)
print('number of dimensions :', new.ndim)     

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
new= np.array([1, 2, 3, 4], ndmin=5)


In [60]:
new= np.array([1, 2, 3, 4], dtype=complex)
new

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [61]:
new= np.array([1, 2, 3, 4], dtype=str)
new

array(['1', '2', '3', '4'], dtype='<U1')

In [62]:
new= np.array([1, 2, 3, 4], dtype=int)
new

array([1, 2, 3, 4])

In [63]:
new= np.array([1, 2, 3, 4], dtype=float)
new

array([1., 2., 3., 4.])

In [64]:
np.dtype

numpy.dtype

In [65]:
x=np.dtype(np.int32)
print(x)

int32


In [69]:
x=np.dtype('i2')
x

dtype('int16')

In [72]:
#create structure datatype
x=np.dtype([("age","i4")])
x

dtype([('age', '<i4')])

In [80]:
a = np.array([(10),(20),(30)],dtype=x)
a

array([(10,), (20,), (30,)], dtype=[('age', '<i4')])

In [83]:
a['age']

array([10, 20, 30])

In [87]:
student=np.dtype([("name","S20"),("age","i1"),("mark","f2")])
student
student["name"]

dtype('S20')

In [91]:
a = np.array([("student1",10,23),("student2",20,78.09),("student3",30,78.0)],dtype=student)
a

array([(b'student1', 10, 23.  ), (b'student2', 20, 78.06),
       (b'student3', 30, 78.  )],
      dtype=[('name', 'S20'), ('age', 'i1'), ('mark', '<f2')])

In [19]:
new = np.array([1, 2, 3, 4])

print(new[1]+new[2])

5


In [23]:
#indexing
new = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print( new[0, 1])

2


In [26]:
new = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(new[0, 0, 2])

3


In [28]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('negative indexing ', arr[-1, -1])

negative indexing  10


In [31]:
new = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[11,12,13,14,15], [16,17,18,19,10]]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [36]:
#1D to 2D

new = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,34,56,67])
new1 = new.reshape(5, 3)
print(new1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [34 56 67]]


In [46]:
new = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18])
new1 = new.reshape(2, 3,3)
new1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
for i,j in enumerate (new1):
    print(i)
    print(j)

0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [57]:
for i in new1:
    for k,j in enumerate (i):
        print(k)
        print(j)

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]
0
[10 11 12]
1
[13 14 15]
2
[16 17 18]


In [59]:
for i in new1:
    for j in i:
        for k ,l in enumerate (j):
            print(k,"index")
            print(l)

0 index
1
1 index
2
2 index
3
0 index
4
1 index
5
2 index
6
0 index
7
1 index
8
2 index
9
0 index
10
1 index
11
2 index
12
0 index
13
1 index
14
2 index
15
0 index
16
1 index
17
2 index
18
